version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - kafka
      - zookeeper
      - akhq
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1 #define id do broker
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 #define o endereço do zookeeper
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 #define o endereço do broker e PLAINTEXT para não usar SSL(criptografia)
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT #define o protocolo de segurança
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 #define o fator de replicação do tópico , 1 para ambiente de desenvolvimento
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true  #define se o tópico será criado automaticamente
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  akhq: #interface gráfica para gerenciamento do kafka
    image: tchiotludo/akhq:latest
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka